from openapi_test_client.libraries.core.endpoints.endpoint_factory import endpoint
from openapi_test_client.libraries.openapi.base.api_class import OpenAPIBase
from openapi_test_client.libraries.openapi.endpoints.endpoint import Endpoint
from openapi_test_client.libraries.openapi.endpoints.endpoint_func import EndpointFunc

# Override __module__ so that import code generated by code gen to look like it's importing from this module
endpoint.__module__ = __name__

__all__ = ["Endpoint", "EndpointFunc", "OpenAPIBase", "endpoint"]
