[tox]
env_list =
    linting
    py{311,312,313,314}

[testenv]
set_env =
    IS_TOX = true
extras = app
dependency_groups = test
commands = pytest {posargs:-n auto}

# Use a different app port per env for parallel testing
[testenv:py311]
set_env =
    IS_TOX = true

[testenv:py312]
set_env =
    IS_TOX = true

[testenv:py313]
set_env =
    IS_TOX = true

[testenv:py314]
set_env =
    IS_TOX = true

[testenv:linting]
runner = uv-venv-lock-runner
package = editable
dependency_groups = lint
commands = pre-commit run --all-files --show-diff-on-failure
