version: 1
handlers:
  console:
    class: common_libs.logging.ColoredStreamHandler
    formatter: default
    stream: ext://sys.stdout
formatters:
  default:
    class: common_libs.logging.LogFormatter
    format: "%(asctime)s - %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S.%f%z"
loggers:
  common_libs:
    level: DEBUG
    handlers:
      - console
  openapi_test_client:
    level: DEBUG
    handlers:
      - console
