version: 1
disable_existing_loggers: false
handlers:
  console:
    class: common_libs.logging.ColoredStreamHandler
    formatter: default
    stream: ext://sys.stdout
formatters:
  default:
    class: common_libs.logging.LogFormatter
loggers:
  openapi_test_client:
    level: DEBUG
    handlers:
      - console
    propagate: false
  api_client_core:
    level: DEBUG
    handlers:
      - console
    propagate: false
