"""
This file was automatically generated by a script.
Do NOT manually update the content.
"""

from dataclasses import dataclass
from typing import Annotated, Literal

from openapi_test_client.libraries.api.types import Constraint, Format, Optional, ParamModel


@dataclass
class Preferences(ParamModel):
    theme: Optional[Literal["light", "dark", "system"]] = ...
    language: Optional[str] = ...
    font_size: Optional[Annotated[int, Constraint(min=8, max=40, multiple_of=2)]] = ...


@dataclass
class SocialLinks(ParamModel):
    facebook: Optional[Annotated[str, Format("uri"), Constraint(min_len=1)]] = ...
    instagram: Optional[Annotated[str, Format("uri"), Constraint(min_len=1)]] = ...
    linkedin: Optional[Annotated[str, Format("uri"), Constraint(min_len=1)]] = ...
    github: Optional[Annotated[str, Format("uri"), Constraint(min_len=1)]] = ...


@dataclass
class Metadata(ParamModel):
    preferences: Optional[Preferences] = ...
    social_links: Optional[SocialLinks] = ...
